<a href="https://colab.research.google.com/github/princoo/pytorch-in-ML/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.3.1+cu121


# introduction to tensors

### creating a **tensor**

In [ ]:
#  scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#  a scaler has 0 dimention
scalar.ndim

0

In [ ]:
#  getting the item in the scalar
scalar.item()

7

In [ ]:
#  vectors
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
#  dimention of vector is not zero (nbr of arrays i think)
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#  MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
#  TENSORS
# prompt: generate a 2,4,4 tensor data
TENSOR = torch.tensor([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12],
                        [13,14,15,16]],
                       [[17,18,19,20],
                        [21,22,23,24],
                        [25,26,27,28],
                        [29,30,31,32]]])
TENSOR
TENSOR.ndim
TENSOR.shape


torch.Size([2, 4, 4])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 4, 4])

### Random tensors

In [ ]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.1027, 0.7028, 0.4853, 0.3586],
         [0.0075, 0.3113, 0.5999, 0.0838],
         [0.2112, 0.6088, 0.5566, 0.4436]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(1,244,244))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([1, 244, 244]), 3)

### Zeros and ones

In [ ]:
#  a tensor with all zeros
zeros = torch.zeros(3,4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
#  a tensor with all ones
ones = torch.ones(3,4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like¶


In [ ]:
#  we use torch.arange()
zero_to_ten = torch.arange(start=1, end=11, step=1)
zero_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#  creating tensor like

ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tenso datatypes

In [ ]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False # whether on not to track gradient with this tensor operation
                               )
float_32_tensor.shape, float_32_tensor.dtype

tensor([3., 6., 9.])

In [ ]:
#  how to change the datatype of a tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

###Getting information from tensors¶


In [ ]:
# create a random tensor

random_tensor= torch.rand(3,4)
random_tensor

tensor([[0.7639, 0.5762, 0.9784, 0.0665],
        [0.3537, 0.1211, 0.7010, 0.4052],
        [0.8075, 0.3285, 0.6380, 0.6402]])

In [ ]:
#  getting the tensor information
print(random_tensor)
print(f"the type of the tensor is: {random_tensor.dtype}")
print(f"the device of the tensor is: {random_tensor.device}")

In [ ]:
#  lets play around and change the tensor datatype

rando_tensor_modified=random_tensor.type(torch.half) # half is same as float16
print(f"now the type of the tensor is: {rando_tensor_modified.dtype}")

now the type of the tensor is: torch.float16


### Manipulating tensors (tensor operations)¶


In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3])

#  NOTE THAT THE TENSOR VALUE DOESNT CHANGE UNLESS ITS REASSIGNED
#  LIKE tensor = tensor +10
#  addition
tensor + 10

tensor([11, 12, 13])

In [ ]:
#  multiplication
tensor * 10


tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
#  subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# try out pytorch built in functions

torch.mul(tensor, 10) # will multipy each ele by 10

tensor([10, 20, 30])

### matrix multiplication
Two main ways to perfom this
1. Element-wise multiplication
2. Matrix multiplication (dot product)

there are 2 main rules that perfoming matrix multiplication needs to satisfy:
1. the inner dimentions must match:
* `(3,2) @(3,2) Wont work`
* `(2,3) @(2,3) will work`
* `(3,2) @(2,3) will work`
2. the resulting matrix has the shape of the outer matrix
* `(2,3) @(3,2) Wont work` -> `(2,2)`
* `(3,2) @(2,3) Wont work` -> `(3,3)`
  

In [ ]:
#  eg matrix multiplication
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.0990, 0.8247],
        [0.9249, 0.1646]])

In [ ]:
#  Element-wise multiplication
print (tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#  Matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

### One of the most common errors in deep learning: shape error

To fix our tensor issues. we can manupulate the shape of one of our tensors using **transpose**

In [ ]:
tensor_B = torch.rand(3,2)
tensor_A = torch.rand(3,2)

In [ ]:
torch.matmul(tensor_A, tensor_B) # this will result in a shape error

In [ ]:
#  now lets try to use transpose on one of our tensors

tensor_B.T , tensor_B.T.shape
#  you will see that after the transpose the shape is changed


(tensor([[0.3205, 0.7407, 0.5365],
         [0.1738, 0.4327, 0.1312]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[0.4250, 1.0058, 0.5899],
        [0.3160, 0.7520, 0.4168],
        [0.1563, 0.3842, 0.1431]])

## Finding the min, max, mean, sum, etc (aggregation)

In [4]:
#  create a tensor

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
# max and min
x.max(), x.min()

#  or you can use torch.max(x) , torch.min(x)

(tensor(90), tensor(0))

In [11]:
#  mean
# - Note: the torch.mean() function requires a tensor of float32 to work
torch.mean(x.type(torch.float32))

#  or you can also use x.type(torch.float32).mean()

tensor(45.)

## finding the position (index) of min and max

In [12]:
#  this will get the index of the minimum element in the tensor
x.argmin()

tensor(0)

In [13]:
#  this will get the index of the max element in the tensor
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors


In [19]:
#   create a torch
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [22]:
#  reshaping : lets maybe add an extra dimention
x_reshaped = x.reshape(1,9)
#  or also x_reshaped = x.reshape(9,1)

x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [23]:
#  change the view
z = x.view(1,9)
z, z.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [26]:
# changing z will change x cz z shares the same memory as the original input

z[:,1] = 5
z,x

(tensor([[1, 5, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 5, 3, 4, 5, 6, 7, 8, 9]))

In [33]:
#  stack tensors on top of each other
x_stacked = torch.stack((x,x), dim=0)
x_stacked
# dimension to insert. Has to be between 0 and the number of dimensions of concatenated tensors (inclusive). Default: 0

tensor([[1, 5, 3, 4, 5, 6, 7, 8, 9],
        [1, 5, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
#  squezzing

x_squezz = torch.rand(2,1,2,2,1)
x_squezz

In [39]:
# now lets squezz at a specific index
# Returns a tensor with all specified dimensions of input of size 1 removed.
y = torch.squeeze(x_squezz,3)
y.shape
#  you can also use x_squezz.squezze()

torch.Size([2, 1, 2, 2, 1])

In [ ]:
# now lets unsquezz at a specific index
# Returns a new tensor with a dimension of size one inserted at the specified position.
x_unsquezz = torch.tensor([1,2,3,4])
torch.unsqueeze(x_unsquezz, dim=1)
#  you can also use x_unsquezz.unsquezze(dim=1)

In [55]:
# torch.permute - rearranges the dimentions of the target in a specified order
#  Permute returns a view

x_original = torch.rand(size=(244,244,3)) # [heigth, width, color_channel

# lets permute the original tensor to rearange the axis order

x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
x_permuted.shape


torch.Size([3, 244, 244])

## Indexing (selecting data from tensors)
similar with NumPy

In [56]:
#  create a tensor
x =  torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [57]:
# lets index on our first tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
# lets index on middle  bracket (dim=1)
x[0][0]
#  you can also use x[0,0]

tensor([1, 2, 3])

In [62]:
# lets index on the  most inner bracket (last dim)
x[0][0][0]

1

In [66]:
x[0][2][2]

tensor(9)

In [69]:
#  you can also use the : to select all of a target dim
x[:,:,0]

tensor([[1, 4, 7]])

## PyTorch tensors & NumPy

1.   from np to tensor -> torch .from_numpy
2.   from tensor to np -> tensor.numpy()



In [70]:
import torch
import numpy as np

#  numpy to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
# warning  when converting from np to tensor pytorch reflects np default dtype of float64 unless you specify otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [72]:
#  tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))