<a href="https://colab.research.google.com/github/princoo/pytorch-in-ML/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.3.1+cu121


# introduction to tensors

### creating a **tensor**

In [4]:
#  scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
#  a scaler has 0 dimention
scalar.ndim

0

In [6]:
#  getting the item in the scalar
scalar.item()

7

In [3]:
#  vectors
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
#  dimention of vector is not zero (nbr of arrays i think)
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#  MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
#  TENSORS
# prompt: generate a 2,4,4 tensor data
TENSOR = torch.tensor([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12],
                        [13,14,15,16]],
                       [[17,18,19,20],
                        [21,22,23,24],
                        [25,26,27,28],
                        [29,30,31,32]]])
TENSOR
TENSOR.ndim
TENSOR.shape


torch.Size([2, 4, 4])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([2, 4, 4])

### Random tensors

In [20]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.1027, 0.7028, 0.4853, 0.3586],
         [0.0075, 0.3113, 0.5999, 0.0838],
         [0.2112, 0.6088, 0.5566, 0.4436]]])

In [21]:
random_tensor.ndim

3

In [22]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(1,244,244))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([1, 244, 244]), 3)

### Zeros and ones

In [24]:
#  a tensor with all zeros
zeros = torch.zeros(3,4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [25]:
#  a tensor with all ones
ones = torch.ones(3,4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like¶


In [27]:
#  we use torch.arange()
zero_to_ten = torch.arange(start=1, end=11, step=1)
zero_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
#  creating tensor like

ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tenso datatypes

In [33]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False # whether on not to track gradient with this tensor operation
                               )
float_32_tensor.shape, float_32_tensor.dtype

tensor([3., 6., 9.])

In [34]:
#  how to change the datatype of a tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

###Getting information from tensors¶


In [37]:
# create a random tensor

random_tensor= torch.rand(3,4)
random_tensor

tensor([[0.7639, 0.5762, 0.9784, 0.0665],
        [0.3537, 0.1211, 0.7010, 0.4052],
        [0.8075, 0.3285, 0.6380, 0.6402]])

In [ ]:
#  getting the tensor information
print(random_tensor)
print(f"the type of the tensor is: {random_tensor.dtype}")
print(f"the device of the tensor is: {random_tensor.device}")

In [43]:
#  lets play around and change the tensor datatype

rando_tensor_modified=random_tensor.type(torch.half) # half is same as float16
print(f"now the type of the tensor is: {rando_tensor_modified.dtype}")

now the type of the tensor is: torch.float16


### Manipulating tensors (tensor operations)¶


In [50]:
# create a tensor
tensor = torch.tensor([1,2,3])

#  NOTE THAT THE TENSOR VALUE DOESNT CHANGE UNLESS ITS REASSIGNED
#  LIKE tensor = tensor +10
#  addition
tensor + 10

tensor([11, 12, 13])

In [51]:
#  multiplication
tensor * 10


tensor([10, 20, 30])

In [52]:
tensor

tensor([1, 2, 3])

In [53]:
#  subtract 10
tensor - 10

tensor([-9, -8, -7])

In [54]:
# try out pytorch built in functions

torch.mul(tensor, 10) # will multipy each ele by 10

tensor([10, 20, 30])

### matrix multiplication
Two main ways to perfom this
1. Element-wise multiplication
2. Matrix multiplication (dot product)

there are 2 main rules that perfoming matrix multiplication needs to satisfy:
1. the inner dimentions must match:
* `(3,2) @(3,2) Wont work`
* `(2,3) @(2,3) will work`
* `(3,2) @(2,3) will work`
2. the resulting matrix has the shape of the outer matrix
* `(2,3) @(3,2) Wont work` -> `(2,2)`
* `(3,2) @(2,3) Wont work` -> `(3,3)`
  

In [60]:
#  eg matrix multiplication
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.0990, 0.8247],
        [0.9249, 0.1646]])

In [55]:
#  Element-wise multiplication
print (tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [56]:
#  Matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

### One of the most common errors in deep learning: shape error

To fix our tensor issues. we can manupulate the shape of one of our tensors using **transpose**

In [62]:
tensor_B = torch.rand(3,2)
tensor_A = torch.rand(3,2)

In [ ]:
torch.matmul(tensor_A, tensor_B) # this will result in a shape error

In [67]:
#  now lets try to use transpose on one of our tensors

tensor_B.T , tensor_B.T.shape
#  you will see that after the transpose the shape is changed


(tensor([[0.3205, 0.7407, 0.5365],
         [0.1738, 0.4327, 0.1312]]),
 torch.Size([2, 3]))

In [72]:
torch.mm(tensor_A, tensor_B.T)

tensor([[0.4250, 1.0058, 0.5899],
        [0.3160, 0.7520, 0.4168],
        [0.1563, 0.3842, 0.1431]])

## Finding the min, max, mean, sum, etc (aggregation)